name: "Security report"
description: "Create a report to vulnerability or other security things"
title: "[SECURITY] <description>"
labels: [security]
body:
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: Provide a general summary of the secure problem you found
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this security report?
    validations:
      required: false
