name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get latest IR
        run: |
          curl -o ./ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/darwin-amd64.cpp

      - name: Compile Latest JuleC IR
        run: |
          mkdir ./bin
          clang++ -O0 --std=c++17 -Wno-everything -o ./bin/julec ./ir.cpp
          git update-index --add --chmod=-x ./bin/julec
          chmod +x ./bin/julec
          
      - name: JuleC Version
        run: |
          ./bin/julec version

      - name: Test - Array OOP
        run: |
          ./bin/julec -t ./tests/array_oop
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test
          
      - name: Test - Basic Calculator
        run: |
          ./bin/julec -t ./tests/basic_calculator
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          
      - name: Test - Levenshtein Distance
        run: |
          ./bin/julec -t ./tests/levenshtein_distance
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test
          
      - name: Test - Map OOP
        run: |
          ./bin/julec -t ./tests/map_oop
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test

      - name: Test - QuickSort
        run: |
          ./bin/julec -t ./tests/quicksort
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test
          
      - name: Test - Str OOP
        run: |
          ./bin/julec -t ./tests/str_oop
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test

      - name: Test - Syntax
        run: |
          ./bin/julec -t ./tests/syntax
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test

      - name: Test - Traits
        run: |
          ./bin/julec -t ./tests/traits
          clang++ -O0 --std=c++17 -Wno-everything -o ./test ./dist/ir.cpp
          git update-index --add --chmod=-x ./test
          chmod +x ./test
          ./test
